// src/components/admin/bookings/sampleBookings.js
// Placeholder dataset carried over from the original ManageBookingsPage.
// The backend does not expose an admin bookings endpoint yet, so this data
// keeps the dashboard usable. Remove once /api/admin/bookings goes live
// (see bookingsApi.js).

export const SAMPLE_BOOKINGS = [
  {
    id: 'LD001',
    customerName: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    trip: 'Kashmir Valley Tour',
    travelDate: '2025-08-15',
    pax: 4,
    budget: 150000,
    status: 'new',
    temperature: 'hot',
    lastContact: '2025-08-01',
    agent: 'Priya Sharma',
    destination: 'Kashmir',
    notes: 'Family trip for anniversary celebration',
    communications: [
      { type: 'call', date: '2025-08-01', note: 'Initial inquiry call' },
      { type: 'whatsapp', date: '2025-07-30', note: 'Sent package details' },
    ],
    annotations: 'VIP customer - previous booking worth ₹2L',
  },
  {
    id: 'LD002',
    customerName: 'Sneha Patel',
    phone: '+91 87654 32109',
    trip: 'Goa Beach Holiday',
    travelDate: '2025-08-20',
    pax: 2,
    budget: 80000,
    status: 'contacted',
    temperature: 'warm',
    lastContact: '2025-07-28',
    agent: 'Amit Singh',
    destination: 'Goa',
    notes: 'Honeymoon package inquiry',
    communications: [
      { type: 'email', date: '2025-07-28', note: 'Sent brochure' },
    ],
    annotations: 'Prefers luxury accommodations',
  },
  {
    id: 'LD003',
    customerName: 'Mohammed Ali',
    phone: '+91 76543 21098',
    trip: 'Rajasthan Heritage Tour',
    travelDate: '2025-09-10',
    pax: 6,
    budget: 300000,
    status: 'itinerary_shared',
    temperature: 'hot',
    lastContact: '2025-08-02',
    agent: 'Kavita Joshi',
    destination: 'Rajasthan',
    notes: 'Corporate group booking',
    communications: [
      { type: 'call', date: '2025-08-02', note: 'Discussed itinerary changes' },
      { type: 'email', date: '2025-08-01', note: 'Sent revised itinerary' },
    ],
    annotations: 'Decision maker - ready to book',
  },
  {
    id: 'LD004',
    customerName: 'Anita Desai',
    phone: '+91 65432 10987',
    trip: 'Kerala Backwaters',
    travelDate: '2025-08-25',
    pax: 3,
    budget: 120000,
    status: 'quotation_sent',
    temperature: 'warm',
    lastContact: '2025-07-30',
    agent: 'Rohit Mehta',
    destination: 'Kerala',
    notes: 'Elderly parents travel',
    communications: [
      { type: 'email', date: '2025-07-30', note: 'Quotation sent' },
    ],
    annotations: 'Price sensitive - negotiate if needed',
  },
  {
    id: 'LD005',
    customerName: 'Vikram Singh',
    phone: '+91 54321 09876',
    trip: 'Himachal Adventure',
    travelDate: '2025-08-12',
    pax: 8,
    budget: 200000,
    status: 'booked',
    temperature: 'hot',
    lastContact: '2025-08-03',
    agent: 'Priya Sharma',
    destination: 'Himachal Pradesh',
    notes: 'Adventure enthusiasts group',
    communications: [
      { type: 'call', date: '2025-08-03', note: 'Booking confirmed' },
      { type: 'email', date: '2025-08-02', note: 'Payment received' },
    ],
    annotations: 'Confirmed booking - send welcome kit',
  },
];
